server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/up
    username: ${DB_NAME}
    password: ${DB_PWD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jwt:
    key: ${JWT_SECRET_KEY}
    access: ${JWT_ACCESS}
    refresh: ${JWT_REFRESH}


  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true